packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.5.4
  '@types/node': 24.13.3
  typescript: 5.9.3

saveExact: true

allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - temporal-polyfill@1.0.3
overrides:
  postcss: '>=8.5.10'
