export const DISC_LOOKS = ['burn', 'label', 'press', 'rw', 'tape'] as const

export type DiscLook = (typeof DISC_LOOKS)[number]

export type Disc = {
  id: string
  title: string
  oneLiner: string
  note: string
  url: string
  pressed: number
  stack: string
  status: 'pressed' | 'test-pressing'
  hue: number
  look: DiscLook
}

export const DISCS: Disc[] = [
  {
    id: 'clave',
    title: 'clave',
    oneLiner: 'Identity escrow where the platform holds no key.',
    note: 'hold nothing',
    url: 'https://clave.sospedra.me',
    pressed: 2026,
    stack: 'TypeScript, threshold IBE, cut-and-choose',
    status: 'test-pressing',
    hue: 305,
    look: 'rw',
  },
  {
    id: 'irc',
    title: 'irc',
    oneLiner: 'Browser-to-browser chat over a peer mesh.',
    note: 'no servers inside',
    url: 'https://irc.sospedra.me',
    pressed: 2026,
    stack: 'WebRTC, Nostr',
    status: 'test-pressing',
    hue: 245,
    look: 'burn',
  },
  {
    id: 'melchor',
    title: 'melchor',
    oneLiner: 'Wishlists with secret gift reservations.',
    note: 'no duplicate gifts',
    url: 'https://melchor.app',
    pressed: 2026,
    stack: 'Next, Tailwind',
    status: 'pressed',
    hue: 355,
    look: 'press',
  },
  {
    id: 'cims',
    title: 'cims',
    oneLiner: 'A terrain console over the Catalan peaks.',
    note: 'twelve peaks',
    url: 'https://sospedra.me/cims',
    pressed: 2026,
    stack: 'three.js, 30 m terrain',
    status: 'test-pressing',
    hue: 127,
    look: 'label',
  },
  {
    id: 'games',
    title: 'games',
    oneLiner: 'A game archive on a console memory browser.',
    note: 'press start',
    url: 'https://sospedra.me/games',
    pressed: 2026,
    stack: 'React, CSS, WebAudio',
    status: 'test-pressing',
    hue: 25,
    look: 'press',
  },
  {
    id: 'camera',
    title: 'camera',
    oneLiner: 'A midnight photo booth that prints instant film.',
    note: 'hold still',
    url: 'https://sospedra.me/camera',
    pressed: 2026,
    stack: 'MediaDevices, canvas',
    status: 'test-pressing',
    hue: 190,
    look: 'tape',
  },
  {
    id: 'styles',
    title: 'style lab',
    oneLiner: 'Six aesthetics stolen for an afternoon.',
    note: 'six accents',
    url: 'https://sospedra.me/styles',
    pressed: 2026,
    stack: 'CSS, SVG filters, WebGL',
    status: 'test-pressing',
    hue: 320,
    look: 'label',
  },
  {
    id: 'stv',
    title: 'sportv',
    oneLiner: 'What sport is on TV in Spain.',
    note: 'kickoff times',
    url: 'https://sportv.sospedra.me',
    pressed: 2022,
    stack: 'Next, cheerio',
    status: 'test-pressing',
    hue: 175,
    look: 'press',
  },
  {
    id: 'olympics',
    title: 'olympics',
    oneLiner: 'Tokyo 2020 results, frozen in amber.',
    note: 'tokyo, kept frozen',
    url: 'https://olympics.sospedra.me',
    pressed: 2021,
    stack: 'Static snapshot',
    status: 'test-pressing',
    hue: 95,
    look: 'label',
  },
  {
    id: 'cavnter',
    title: 'cavnter',
    oneLiner: 'Daily tally counter with a hard max.',
    note: 'every tap counts',
    url: 'https://cavnter.sospedra.me',
    pressed: 2021,
    stack: 'Expo, React Native',
    status: 'pressed',
    hue: 115,
    look: 'rw',
  },
  {
    id: 'bonfire',
    title: 'bonfire',
    oneLiner: 'A quiet fire to sit around.',
    note: 'sit. warm up',
    url: 'https://bonfire.sospedra.me',
    pressed: 2020,
    stack: 'Next, Tailwind',
    status: 'pressed',
    hue: 45,
    look: 'tape',
  },
  {
    id: 'wkc',
    title: 'which key code',
    oneLiner: 'Press any key, read its code.',
    note: 'press any key',
    url: 'https://wkc.sospedra.me',
    pressed: 2019,
    stack: 'Vite, WebGL, WebAudio',
    status: 'test-pressing',
    hue: 210,
    look: 'burn',
  },
  {
    id: 'spg',
    title: 'semantic password generator',
    oneLiner: 'Passwords you can read out loud.',
    note: 'read it out loud',
    url: 'https://spg.sospedra.me',
    pressed: 2017,
    stack: 'TypeScript, zero deps',
    status: 'test-pressing',
    hue: 135,
    look: 'label',
  },
  {
    id: 'len',
    title: 'len',
    oneLiner: 'The typed length of anything.',
    note: 'mind the length',
    url: 'https://www.npmjs.com/package/@sospedra/len',
    pressed: 2017,
    stack: 'TypeScript micro-lib',
    status: 'test-pressing',
    hue: 15,
    look: 'tape',
  },
  {
    id: 'sti',
    title: 'sti',
    oneLiner: 'Semver to integer, safely.',
    note: 'semver, flattened',
    url: 'https://www.npmjs.com/package/@sospedra/sti',
    pressed: 2017,
    stack: 'TypeScript micro-lib',
    status: 'test-pressing',
    hue: 65,
    look: 'press',
  },
  {
    id: 'logatim',
    title: 'logatim',
    oneLiner: 'Isomorphic logger with levels and ANSI styles.',
    note: 'logs, in color',
    url: 'https://www.npmjs.com/package/logatim',
    pressed: 2016,
    stack: 'TypeScript, ESM',
    status: 'test-pressing',
    hue: 270,
    look: 'rw',
  },
  {
    id: 'rfm',
    title: 'rfm',
    oneLiner: 'Live issue search over the old repo.',
    note: 'still answering',
    url: 'https://rfm.sospedra.me',
    pressed: 2016,
    stack: 'GitHub issues API',
    status: 'test-pressing',
    hue: 335,
    look: 'burn',
  },
]
