import type {
  CrosswordDirection,
  CrosswordEntry,
  CrosswordLocale,
} from './crossword-data'
import type { SolveMode } from './crossword-settings'

export const COPY = {
  en: {
    brand: 'Crosswords',
    edition: (size: string) => `Daily / ${size}`,
    issue: 'Puzzle No. 208',
    publicationLine: 'Bilingual edition',
    languageEdition: 'English edition',
    price: 'Price · 1½d',
    pageNumber: 'Page 01',
    forecast: 'Ready',
    printedBy: 'Sospedra Studio',
    puzzleDesk: 'Grid · 15 × 15',
    frontPage: 'Daily puzzle',
    leadDeckLabel: 'Crossword',
    engravingCaption: 'The presses never sleep',
    belowFold: 'Clues',
    progressLoading: 'Loading',
    clueProgress: (solved: number, total: number) =>
      `${solved} of ${total} clues solved`,
    allFiled: 'Complete',
    filed: 'Done',
    dailyCrossword: 'Daily crossword',
    tools: 'Crossword tools',
    home: 'Home',
    language: 'Puzzle language',
    english: 'English',
    spanish: 'Español',
    by: 'By',
    inkStatus: 'Ready',
    timer: 'Timer',
    pause: 'Pause',
    resume: 'Resume',
    pausedAnnouncement: 'Puzzle paused.',
    resumedAnnouncement: 'Puzzle resumed.',
    pencil: 'Pencil',
    pencilLabel: 'Pencil mode',
    pencilHint: 'Enter tentative letters in a lighter style.',
    pencilOn: 'Pencil mode on.',
    pencilOff: 'Pencil mode off.',
    check: 'Check',
    checkLabel: 'Check answers',
    checkHint: 'Mark mistakes without changing your letters.',
    reveal: 'Reveal',
    revealLabel: 'Reveal answers',
    revealHint: 'Fill correct letters and mark them as revealed.',
    settings: 'Settings',
    help: 'Help',
    more: 'More',
    across: 'Across',
    down: 'Down',
    gridInstructions:
      'Use letter keys to answer, arrows to move, Enter to change direction, and Escape to leave the grid.',
    row: 'Row',
    column: 'column',
    blank: 'Blank',
    letter: 'Letter',
    intersection: 'Intersects',
    revealed: 'Revealed',
    pencilled: 'Pencil entry',
    checked: 'Checked',
    incorrect: 'Incorrect',
    paused: 'Paused',
    pausedNote: 'The timer has stopped.',
    checkTitle: 'Check your work',
    checkNote: 'Checking marks mistakes but never changes a letter.',
    checkCell: 'Check cell',
    checkAnswer: 'Check answer',
    checkPuzzle: 'Check puzzle',
    revealTitle: 'Reveal letters',
    revealNote:
      'Revealed letters stay marked and will be noted in your result.',
    revealCell: 'Reveal cell',
    revealAnswer: 'Reveal answer',
    revealPuzzle: 'Reveal puzzle',
    cancel: 'Cancel',
    close: 'Close',
    settingsTitle: 'Settings',
    solveMode: 'Solve difficulty',
    solveModeNote:
      'Today’s grid stays the same. Difficulty changes how much help appears beside each clue.',
    guidedMode: 'Guided',
    guidedModeNote: 'Clue and first-letter hint.',
    standardMode: 'Standard',
    standardModeNote: 'Clue only.',
    showTimer: 'Show timer',
    skipFilled: 'Skip filled cells',
    autoCheck: 'Auto-check letters',
    strikeSolvedClues: 'Strike through solved clues',
    keySounds: 'Mechanical keys and typewriter return bell',
    largeText: 'Larger clue text',
    highContrast: 'High-contrast grid',
    assistControl: 'Assist',
    scopeControl: 'Scope',
    soundControl: 'Sound',
    advanceControl: 'Advance',
    proofControl: 'Proof',
    typeControl: 'Type',
    contrastControl: 'Contrast',
    cellScope: 'Cell',
    answerScope: 'Answer',
    puzzleScope: 'Grid',
    soundOff: 'Off',
    soundLow: 'Low',
    soundMedium: 'Medium',
    soundHigh: 'High',
    openCells: 'Open',
    everyCell: 'Every',
    liveProof: 'Live',
    manualProof: 'Manual',
    normalType: 'Normal',
    largeType: 'Large',
    normalContrast: 'Normal',
    highContrastValue: 'High',
    undo: 'Undo',
    redo: 'Redo',
    revealArmed: 'Reveal armed. Activate again to confirm.',
    confirmReveal: 'Confirm',
    revealDisarmed: 'Reveal disarmed.',
    timerShown: 'Timer shown.',
    timerHidden: 'Timer hidden.',
    solved: 'Solved',
    firstLetter: (letter: string) => `starts with ${letter}`,
    helpTitle: 'Keyboard shortcuts',
    keyLetters: 'Enter a letter and move forward',
    keyArrows: 'Move around the grid',
    keyEnter: 'Switch Across and Down',
    keyTab: 'Next or previous clue',
    keySpace: 'Clear and move, or switch direction',
    keyDelete: 'Clear the current cell',
    keyUndo: 'Undo or redo',
    keyEscape: 'Leave the grid',
    completeTitle: 'Crossword complete',
    completeNote: 'Every answer is correct.',
    solvedIn: 'Solved in',
    nextPuzzleIn: 'Next crossword in',
    nextPuzzleReady: 'A new crossword is out. Reload to play.',
    checksUsed: 'Checks used',
    revealsUsed: 'Reveals used',
    copyResult: 'Copy result',
    playAgain: 'Play again',
    restartedAnnouncement: 'Fresh puzzle ready.',
    resultCopied: 'Result copied.',
    notCorrect: 'The grid is full, but one answer is still incorrect.',
    noErrors: 'No errors found in that selection.',
    errorsFound: (count: number) =>
      `${count} ${count === 1 ? 'correction' : 'corrections'} marked.`,
    revealDone: 'The selected letters were revealed.',
    directionChanged: (direction: string) => `${direction} selected.`,
    clueList: 'Clues',
    switchToAcross: 'Show Across clues',
    switchToDown: 'Show Down clues',
    gridLabel: (date: string, size: string) =>
      `English crossword, ${date}, ${size}`,
    inputLabel: 'Crossword letter input',
    begin: 'Start',
    startHint: 'The clock starts when you do.',
    startedAnnouncement: 'Clock running.',
    legendTitle: 'Grid marks',
    legendChecked: 'Green underline: verified correct by Check.',
    legendRevealed: 'Red underline and dot: letter revealed for you.',
    legendIncorrect: 'Red cell: marked wrong by Check.',
  },
  es: {
    brand: 'Crucigrama',
    edition: (size: string) => `Diario / ${size}`,
    issue: 'Crucigrama n.º 208',
    publicationLine: 'Edición bilingüe',
    languageEdition: 'Edición en español',
    price: 'Precio · 1½ p.',
    pageNumber: 'Página 01',
    forecast: 'Listo',
    printedBy: 'Sospedra Studio',
    puzzleDesk: 'Cuadrícula · 15 × 15',
    frontPage: 'Crucigrama diario',
    leadDeckLabel: 'Crucigrama',
    engravingCaption: 'Las prensas nunca duermen',
    belowFold: 'Pistas',
    progressLoading: 'Cargando',
    clueProgress: (solved: number, total: number) =>
      `${solved} de ${total} pistas resueltas`,
    allFiled: 'Completo',
    filed: 'Hecho',
    dailyCrossword: 'Crucigrama diario',
    tools: 'Herramientas del crucigrama',
    home: 'Inicio',
    language: 'Idioma del crucigrama',
    english: 'English',
    spanish: 'Español',
    by: 'Por',
    inkStatus: 'Listo',
    timer: 'Cronómetro',
    pause: 'Pausar',
    resume: 'Continuar',
    pausedAnnouncement: 'Crucigrama en pausa.',
    resumedAnnouncement: 'Crucigrama reanudado.',
    pencil: 'Lápiz',
    pencilLabel: 'Modo lápiz',
    pencilHint: 'Introduce letras provisionales con un estilo más tenue.',
    pencilOn: 'Modo lápiz activado.',
    pencilOff: 'Modo lápiz desactivado.',
    check: 'Comprobar',
    checkLabel: 'Comprobar respuestas',
    checkHint: 'Marca los errores sin cambiar tus letras.',
    reveal: 'Revelar',
    revealLabel: 'Revelar respuestas',
    revealHint: 'Completa las letras correctas y las marca como reveladas.',
    settings: 'Ajustes',
    help: 'Ayuda',
    more: 'Más',
    across: 'Horizontales',
    down: 'Verticales',
    gridInstructions:
      'Usa letras para responder, flechas para moverte, Intro para cambiar de dirección y Escape para salir de la cuadrícula.',
    row: 'Fila',
    column: 'columna',
    blank: 'Vacía',
    letter: 'Letra',
    intersection: 'Cruza con',
    revealed: 'Revelada',
    pencilled: 'Letra a lápiz',
    checked: 'Comprobada',
    incorrect: 'Incorrecta',
    paused: 'En pausa',
    pausedNote: 'El cronómetro se ha detenido.',
    checkTitle: 'Comprobar respuestas',
    checkNote: 'La comprobación marca errores, pero no cambia letras.',
    checkCell: 'Comprobar casilla',
    checkAnswer: 'Comprobar respuesta',
    checkPuzzle: 'Comprobar crucigrama',
    revealTitle: 'Revelar letras',
    revealNote:
      'Las letras reveladas quedan marcadas y constarán en el resultado.',
    revealCell: 'Revelar casilla',
    revealAnswer: 'Revelar respuesta',
    revealPuzzle: 'Revelar crucigrama',
    cancel: 'Cancelar',
    close: 'Cerrar',
    settingsTitle: 'Ajustes',
    solveMode: 'Dificultad',
    solveModeNote:
      'La cuadrícula de hoy no cambia. La dificultad cambia la ayuda que aparece junto a cada pista.',
    guidedMode: 'Guiado',
    guidedModeNote: 'Pista y primera letra.',
    standardMode: 'Estándar',
    standardModeNote: 'Solo la pista.',
    showTimer: 'Mostrar cronómetro',
    skipFilled: 'Saltar casillas llenas',
    autoCheck: 'Comprobar letras automáticamente',
    strikeSolvedClues: 'Tachar las pistas resueltas',
    keySounds: 'Teclas mecánicas y campana de retorno de carro',
    largeText: 'Pistas con texto grande',
    highContrast: 'Cuadrícula de alto contraste',
    assistControl: 'Ayuda',
    scopeControl: 'Alcance',
    soundControl: 'Sonido',
    advanceControl: 'Avance',
    proofControl: 'Prueba',
    typeControl: 'Texto',
    contrastControl: 'Contraste',
    cellScope: 'Casilla',
    answerScope: 'Respuesta',
    puzzleScope: 'Cuadrícula',
    soundOff: 'Apagado',
    soundLow: 'Bajo',
    soundMedium: 'Medio',
    soundHigh: 'Alto',
    openCells: 'Libres',
    everyCell: 'Todas',
    liveProof: 'Directa',
    manualProof: 'Manual',
    normalType: 'Normal',
    largeType: 'Grande',
    normalContrast: 'Normal',
    highContrastValue: 'Alto',
    undo: 'Deshacer',
    redo: 'Rehacer',
    revealArmed: 'Revelar preparado. Activa de nuevo para confirmar.',
    confirmReveal: 'Confirmar',
    revealDisarmed: 'Revelado desactivado.',
    timerShown: 'Cronómetro visible.',
    timerHidden: 'Cronómetro oculto.',
    solved: 'Resuelta',
    firstLetter: (letter: string) => `empieza por ${letter}`,
    helpTitle: 'Atajos de teclado',
    keyLetters: 'Escribir una letra y avanzar',
    keyArrows: 'Moverse por la cuadrícula',
    keyEnter: 'Cambiar entre horizontal y vertical',
    keyTab: 'Pista siguiente o anterior',
    keySpace: 'Borrar y avanzar, o cambiar dirección',
    keyDelete: 'Borrar la casilla actual',
    keyUndo: 'Deshacer o rehacer',
    keyEscape: 'Salir de la cuadrícula',
    completeTitle: 'Crucigrama completado',
    completeNote: 'Todas las respuestas son correctas.',
    solvedIn: 'Resuelto en',
    nextPuzzleIn: 'Próximo crucigrama en',
    nextPuzzleReady: 'Hay un crucigrama nuevo. Recarga para jugar.',
    checksUsed: 'Comprobaciones',
    revealsUsed: 'Letras reveladas',
    copyResult: 'Copiar resultado',
    playAgain: 'Volver a jugar',
    restartedAnnouncement: 'Crucigrama nuevo listo.',
    resultCopied: 'Resultado copiado.',
    notCorrect:
      'La cuadrícula está llena, pero aún hay una respuesta incorrecta.',
    noErrors: 'No se encontraron errores en la selección.',
    errorsFound: (count: number) =>
      `${count} ${count === 1 ? 'corrección marcada' : 'correcciones marcadas'}.`,
    revealDone: 'Se revelaron las letras seleccionadas.',
    directionChanged: (direction: string) => `Dirección ${direction}.`,
    clueList: 'Pistas',
    switchToAcross: 'Mostrar pistas horizontales',
    switchToDown: 'Mostrar pistas verticales',
    gridLabel: (date: string, size: string) =>
      `Crucigrama en español, ${date}, ${size}`,
    inputLabel: 'Entrada de letras del crucigrama',
    begin: 'Empezar',
    startHint: 'El cronómetro empieza contigo.',
    startedAnnouncement: 'Cronómetro en marcha.',
    legendTitle: 'Marcas de la cuadrícula',
    legendChecked: 'Subrayado verde: letra verificada con Comprobar.',
    legendRevealed: 'Subrayado rojo y punto: letra revelada.',
    legendIncorrect: 'Casilla roja: marcada como incorrecta al comprobar.',
  },
} as const

export type Copy = (typeof COPY)[CrosswordLocale]

export const directionLabel = (
  direction: CrosswordDirection,
  locale: CrosswordLocale,
) => COPY[locale][direction]

export const clueAssist = (
  entry: CrosswordEntry,
  mode: SolveMode,
  locale: CrosswordLocale,
) => {
  if (mode !== 'guided') return null
  return COPY[locale].firstLetter(entry.gridAnswer[0])
}

export const publicationDateLabel = (
  publicationDate: string,
  locale: CrosswordLocale,
) =>
  new Intl.DateTimeFormat(locale === 'en' ? 'en-US' : 'es-ES', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'UTC',
  }).format(new Date(`${publicationDate}T12:00:00Z`))
