export const stubs = {
  large: 'this is my long sentence to try and to check the length thiny',
  medium: 'a bit more short but medium long',
  small: 'super short',
  elision: "itsn't a thing we'll understand",
  html: `<p><b>Björk Guðmundsdóttir</b> <span class="noexcerpt nowraplinks" style="font-size:85%;"><a href="/wiki/Order_of_the_Falcon" title="Order of the Falcon">OTF</a></span> (<span class="rt-commentedText nowrap"><span class="IPA nopopups noexcerpt"><a href="/wiki/Help:IPA/English" title="Help:IPA/English">/<span style="border-bottom:1px dotted"><span title="'b' in 'buy'">b</span><span title="/j/: 'y' in 'yes'">j</span><span title="/ɜːr/: 'ur' in 'fur'">ɜːr</span><span title="'k' in 'kind'">k</span></span>/</a></,span></span> <a href="/wiki/Help:Pronunciation_respelling_key" title="Help:Pronunciation respelling key"><i title="English pronunciation respelling"><span style="font-size:90%">BYURK</span></i></a>, <small>Icelandic:&nbsp;</small><span title="Representation in the International Phonetic Alphabet (IPA)" class="IPA"><a href="/wiki/Help:IPA/Icelandic" title="Help:IPA/Icelandic">[pjœr̥k ˈkvʏðmʏntsˌtouʰtɪr̥]</a></span> <span class="nowrap" style="font-size:85%">(<span class="unicode haudio"><span class="fn"><span style="white-space:nowrap;margin-right:.25em;"><a href="/wiki/File:Is-Bj%C3%B6rk_Gu%C3%B0mundsd%C3%B3ttir2.ogg" title="About this sound"><img alt="About this sound" src="//upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Loudspeaker.svg/11px-Loudspeaker.svg.png" decoding="async" width="11" height="11" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Loudspeaker.svg/17px-Loudspeaker.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Loudspeaker.svg/22px-Loudspeaker.svg.png 2x" data-file-width="20" data-file-height="20"></a></span><a href="//upload.wikimedia.org/wikipedia/commons/e/e3/Is-Bj%C3%B6rk_Gu%C3%B0mundsd%C3%B3ttir2.ogg" class="internal" title="Is-Björk Guðmundsdóttir2.ogg">listen</a></span></span>)</span>; born 21 November, 1965) is an Icelandic singer, songwriter, record producer, actress, and DJ. Over her four-decade career, she has developed an <a href="/wiki/Eclecticism_in_music" title="Eclecticism in music">eclectic</a> musical style that draws on a range of influences and genres spanning <a href="/wiki/Electronic_music" title="Electronic music">electronic</a>, <a href="/wiki/Pop_music" title="Pop music">pop</a>, <a href="/wiki/Experimental_music" title="Experimental music">experimental</a>, <a href="/wiki/Trip_hop" title="Trip hop">trip hop</a>, <a href="/wiki/Classical_music" title="Classical music">classical</a> and <a href="/wiki/Avant-garde_music" title="Avant-garde music">avant-garde</a> music.</p>`,
  extract: `<p><b>Rapid Evolution</b> (also known as <b>RE</b>) is a software tool for DJs, providing filtering and searching features suitable for musicians.  It can analyze audio files and automatically determine properties such as the musical key, beats per minute (BPM), beat intensity and ReplayGain.↵</p><p>It supports file types MP3, MP4, WAV, FLAC, OGG, AAC and APE.  It helps DJs to organize and profile their music, and assists in the process of mixing music by utilizing song metadata to be able to show</p>...`,
  unicode:
    'Björk Guðmundsdóttir OTF (/bjɜːrk/ BYURK, Icelandic: [pjœr̥k ˈkvʏðmʏntsˌtouʰtɪr̥] (About this soundlisten); born 21 November, 1965) is an Icelandic singer, songwriter, record producer, actress, and DJ. Over her four-decade career, she has developed an eclectic musical style that draws on a range of influences and genres spanning electronic, pop, experimental, trip hop, classical, and avant-garde music.',
}
