import type { LocalizedOption } from './model'

/**
 * Repository-owned display labels for the editorial v1 roster:
 * 192 UN member states, the Holy See (VA), and the State of Palestine (PS).
 *
 * Keep this list independent from the reviewed gameplay corpus. Autocomplete
 * needs country names only and must not ship capital, geometry, difficulty, or
 * eligibility data to the browser.
 *
 * Accepted aliases are deliberately omitted for now. `LocalizedOption`
 * represents one resolvable label per id, so adding aliases as extra options
 * would advertise answers that the current exact-answer resolver cannot grade
 * safely.
 */
const OFFICIAL_COUNTRY_NAMES = [
  ['AD', 'Andorra', 'Andorra'],
  ['AE', 'United Arab Emirates', 'Emiratos Árabes Unidos'],
  ['AF', 'Afghanistan', 'Afganistán'],
  ['AG', 'Antigua and Barbuda', 'Antigua y Barbuda'],
  ['AL', 'Albania', 'Albania'],
  ['AM', 'Armenia', 'Armenia'],
  ['AO', 'Angola', 'Angola'],
  ['AR', 'Argentina', 'Argentina'],
  ['AT', 'Austria', 'Austria'],
  ['AU', 'Australia', 'Australia'],
  ['AZ', 'Azerbaijan', 'Azerbaiyán'],
  ['BA', 'Bosnia and Herzegovina', 'Bosnia y Herzegovina'],
  ['BB', 'Barbados', 'Barbados'],
  ['BD', 'Bangladesh', 'Bangladés'],
  ['BE', 'Belgium', 'Bélgica'],
  ['BF', 'Burkina Faso', 'Burkina Faso'],
  ['BG', 'Bulgaria', 'Bulgaria'],
  ['BH', 'Bahrain', 'Baréin'],
  ['BI', 'Burundi', 'Burundi'],
  ['BJ', 'Benin', 'Benín'],
  ['BN', 'Brunei', 'Brunéi'],
  ['BO', 'Bolivia', 'Bolivia'],
  ['BR', 'Brazil', 'Brasil'],
  ['BS', 'Bahamas', 'Bahamas'],
  ['BT', 'Bhutan', 'Bután'],
  ['BW', 'Botswana', 'Botsuana'],
  ['BY', 'Belarus', 'Bielorrusia'],
  ['BZ', 'Belize', 'Belice'],
  ['CA', 'Canada', 'Canadá'],
  ['CD', 'Democratic Republic of the Congo', 'República Democrática del Congo'],
  ['CF', 'Central African Republic', 'República Centroafricana'],
  ['CG', 'Republic of the Congo', 'República del Congo'],
  ['CH', 'Switzerland', 'Suiza'],
  ['CI', 'Côte d’Ivoire', 'Costa de Marfil'],
  ['CL', 'Chile', 'Chile'],
  ['CM', 'Cameroon', 'Camerún'],
  ['CN', 'China', 'China'],
  ['CO', 'Colombia', 'Colombia'],
  ['CR', 'Costa Rica', 'Costa Rica'],
  ['CU', 'Cuba', 'Cuba'],
  ['CV', 'Cabo Verde', 'Cabo Verde'],
  ['CY', 'Cyprus', 'Chipre'],
  ['CZ', 'Czechia', 'Chequia'],
  ['DE', 'Germany', 'Alemania'],
  ['DJ', 'Djibouti', 'Yibuti'],
  ['DK', 'Denmark', 'Dinamarca'],
  ['DM', 'Dominica', 'Dominica'],
  ['DO', 'Dominican Republic', 'República Dominicana'],
  ['DZ', 'Algeria', 'Argelia'],
  ['EC', 'Ecuador', 'Ecuador'],
  ['EE', 'Estonia', 'Estonia'],
  ['EG', 'Egypt', 'Egipto'],
  ['ER', 'Eritrea', 'Eritrea'],
  ['ES', 'Spain', 'España'],
  ['ET', 'Ethiopia', 'Etiopía'],
  ['FI', 'Finland', 'Finlandia'],
  ['FJ', 'Fiji', 'Fiyi'],
  ['FM', 'Micronesia', 'Micronesia'],
  ['FR', 'France', 'Francia'],
  ['GA', 'Gabon', 'Gabón'],
  ['GB', 'United Kingdom', 'Reino Unido'],
  ['GD', 'Grenada', 'Granada'],
  ['GE', 'Georgia', 'Georgia'],
  ['GH', 'Ghana', 'Ghana'],
  ['GM', 'Gambia', 'Gambia'],
  ['GN', 'Guinea', 'Guinea'],
  ['GQ', 'Equatorial Guinea', 'Guinea Ecuatorial'],
  ['GR', 'Greece', 'Grecia'],
  ['GT', 'Guatemala', 'Guatemala'],
  ['GW', 'Guinea-Bissau', 'Guinea-Bisáu'],
  ['GY', 'Guyana', 'Guyana'],
  ['HN', 'Honduras', 'Honduras'],
  ['HR', 'Croatia', 'Croacia'],
  ['HT', 'Haiti', 'Haití'],
  ['HU', 'Hungary', 'Hungría'],
  ['ID', 'Indonesia', 'Indonesia'],
  ['IE', 'Ireland', 'Irlanda'],
  ['IN', 'India', 'India'],
  ['IQ', 'Iraq', 'Irak'],
  ['IR', 'Iran', 'Irán'],
  ['IS', 'Iceland', 'Islandia'],
  ['IT', 'Italy', 'Italia'],
  ['JM', 'Jamaica', 'Jamaica'],
  ['JO', 'Jordan', 'Jordania'],
  ['JP', 'Japan', 'Japón'],
  ['KE', 'Kenya', 'Kenia'],
  ['KG', 'Kyrgyzstan', 'Kirguistán'],
  ['KH', 'Cambodia', 'Camboya'],
  ['KI', 'Kiribati', 'Kiribati'],
  ['KM', 'Comoros', 'Comoras'],
  ['KN', 'Saint Kitts and Nevis', 'San Cristóbal y Nieves'],
  ['KP', 'North Korea', 'Corea del Norte'],
  ['KR', 'South Korea', 'Corea del Sur'],
  ['KW', 'Kuwait', 'Kuwait'],
  ['KZ', 'Kazakhstan', 'Kazajistán'],
  ['LA', 'Laos', 'Laos'],
  ['LB', 'Lebanon', 'Líbano'],
  ['LC', 'Saint Lucia', 'Santa Lucía'],
  ['LI', 'Liechtenstein', 'Liechtenstein'],
  ['LK', 'Sri Lanka', 'Sri Lanka'],
  ['LR', 'Liberia', 'Liberia'],
  ['LS', 'Lesotho', 'Lesoto'],
  ['LT', 'Lithuania', 'Lituania'],
  ['LU', 'Luxembourg', 'Luxemburgo'],
  ['LV', 'Latvia', 'Letonia'],
  ['LY', 'Libya', 'Libia'],
  ['MA', 'Morocco', 'Marruecos'],
  ['MC', 'Monaco', 'Mónaco'],
  ['MD', 'Moldova', 'Moldavia'],
  ['ME', 'Montenegro', 'Montenegro'],
  ['MG', 'Madagascar', 'Madagascar'],
  ['MH', 'Marshall Islands', 'Islas Marshall'],
  ['MK', 'North Macedonia', 'Macedonia del Norte'],
  ['ML', 'Mali', 'Mali'],
  ['MM', 'Myanmar', 'Myanmar'],
  ['MN', 'Mongolia', 'Mongolia'],
  ['MR', 'Mauritania', 'Mauritania'],
  ['MT', 'Malta', 'Malta'],
  ['MU', 'Mauritius', 'Mauricio'],
  ['MV', 'Maldives', 'Maldivas'],
  ['MW', 'Malawi', 'Malaui'],
  ['MX', 'Mexico', 'México'],
  ['MY', 'Malaysia', 'Malasia'],
  ['MZ', 'Mozambique', 'Mozambique'],
  ['NA', 'Namibia', 'Namibia'],
  ['NE', 'Niger', 'Níger'],
  ['NG', 'Nigeria', 'Nigeria'],
  ['NI', 'Nicaragua', 'Nicaragua'],
  ['NL', 'Netherlands', 'Países Bajos'],
  ['NO', 'Norway', 'Noruega'],
  ['NP', 'Nepal', 'Nepal'],
  ['NR', 'Nauru', 'Nauru'],
  ['NZ', 'New Zealand', 'Nueva Zelanda'],
  ['OM', 'Oman', 'Omán'],
  ['PA', 'Panama', 'Panamá'],
  ['PE', 'Peru', 'Perú'],
  ['PG', 'Papua New Guinea', 'Papúa Nueva Guinea'],
  ['PH', 'Philippines', 'Filipinas'],
  ['PK', 'Pakistan', 'Pakistán'],
  ['PL', 'Poland', 'Polonia'],
  ['PS', 'Palestine', 'Palestina'],
  ['PT', 'Portugal', 'Portugal'],
  ['PW', 'Palau', 'Palaos'],
  ['PY', 'Paraguay', 'Paraguay'],
  ['QA', 'Qatar', 'Catar'],
  ['RO', 'Romania', 'Rumanía'],
  ['RS', 'Serbia', 'Serbia'],
  ['RU', 'Russia', 'Rusia'],
  ['RW', 'Rwanda', 'Ruanda'],
  ['SA', 'Saudi Arabia', 'Arabia Saudí'],
  ['SB', 'Solomon Islands', 'Islas Salomón'],
  ['SC', 'Seychelles', 'Seychelles'],
  ['SD', 'Sudan', 'Sudán'],
  ['SE', 'Sweden', 'Suecia'],
  ['SG', 'Singapore', 'Singapur'],
  ['SI', 'Slovenia', 'Eslovenia'],
  ['SK', 'Slovakia', 'Eslovaquia'],
  ['SL', 'Sierra Leone', 'Sierra Leona'],
  ['SM', 'San Marino', 'San Marino'],
  ['SN', 'Senegal', 'Senegal'],
  ['SO', 'Somalia', 'Somalia'],
  ['SR', 'Suriname', 'Surinam'],
  ['SS', 'South Sudan', 'Sudán del Sur'],
  ['ST', 'São Tomé and Príncipe', 'Santo Tomé y Príncipe'],
  ['SV', 'El Salvador', 'El Salvador'],
  ['SY', 'Syria', 'Siria'],
  ['SZ', 'Eswatini', 'Esuatini'],
  ['TD', 'Chad', 'Chad'],
  ['TG', 'Togo', 'Togo'],
  ['TH', 'Thailand', 'Tailandia'],
  ['TJ', 'Tajikistan', 'Tayikistán'],
  ['TL', 'Timor-Leste', 'Timor-Leste'],
  ['TM', 'Turkmenistan', 'Turkmenistán'],
  ['TN', 'Tunisia', 'Túnez'],
  ['TO', 'Tonga', 'Tonga'],
  ['TR', 'Türkiye', 'Turquía'],
  ['TT', 'Trinidad and Tobago', 'Trinidad y Tobago'],
  ['TV', 'Tuvalu', 'Tuvalu'],
  ['TZ', 'Tanzania', 'Tanzania'],
  ['UA', 'Ukraine', 'Ucrania'],
  ['UG', 'Uganda', 'Uganda'],
  ['US', 'United States', 'Estados Unidos'],
  ['UY', 'Uruguay', 'Uruguay'],
  ['UZ', 'Uzbekistan', 'Uzbekistán'],
  ['VA', 'Vatican City', 'Ciudad del Vaticano'],
  ['VC', 'Saint Vincent and the Grenadines', 'San Vicente y las Granadinas'],
  ['VE', 'Venezuela', 'Venezuela'],
  ['VN', 'Vietnam', 'Vietnam'],
  ['VU', 'Vanuatu', 'Vanuatu'],
  ['WS', 'Samoa', 'Samoa'],
  ['YE', 'Yemen', 'Yemen'],
  ['ZA', 'South Africa', 'Sudáfrica'],
  ['ZM', 'Zambia', 'Zambia'],
  ['ZW', 'Zimbabwe', 'Zimbabue'],
] as const

export const OFFICIAL_COUNTRY_OPTIONS: LocalizedOption[] =
  OFFICIAL_COUNTRY_NAMES.map(([code, en, es]) => ({
    id: `country-${code.toLocaleLowerCase('en')}`,
    label: { en, es },
  }))
